runtime: nodejs22

env_variables:
  RECAPTCHA_SITE_KEY: "6LdYdJIpAAAAACdHw2Hipmtpk0U7nzv0hhtIHXmb"
  RECAPTCHA_SECRET_KEY: "6LdYdJIpAAAAAJ7qYLFlanrj2n1V4eeE9lfyrMPt"
  MONGODB_URI: "mongodb+srv://admin:JdNCT3098dvii52g@cluster0.vvyzzdc.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
  JWT_SECRET: "d4305e981fbbe2d9c551d464dd0570845c915584d1c2d8efd859e852a3479d15"
  SESSION_SECRET: "d4305e981fbbe2d9c551d464dd0570845c915584d1c2d8efd859e852a3479d15"
  GOOGLE_CLOUD_PROJECT_ID: "eastern-surface-425418-f4"
  REACT_APP_BASE_API_URL: https://eastern-surface-425418-f4.ew.r.appspot.com


handlers:
  - url: /.*
    script: auto
    secure: always
